name: Deploy to cPanel

on:
  push:
    branches:
      - master  # یا master، بسته به نام برنچ اصلی شما

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftp://avatarvps.com  # دامنه شما
          ftp-username: avatar     # نام کاربری FTP
          ftp-password: DpY3Q[qjcZ;S  # پسورد FTP از Secrets
          local-dir: ./                        # مسیر محلی به دایرکتوری پروژه
          server-dir: /public_html/javaher/            # مسیر در سرور (باید به پوشه‌ای که می‌خواهید فایل‌ها را آپلود کنید اشاره کند)
