name: Deploy to cPanel

on:
  push:
    branches:
      - master  # یا master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: avatarvps.com          # دامنه یا IP سرور شما
          username: avatar    # نام کاربری FTP
          password: DpY3Q[qjcZ;S  # پسورد FTP از Secrets
          protocol: ftp                   # نوع پروتکل
          local-dir: ./                   # مسیر به دایرکتوری محلی
          server-dir: /public_html/javaher/     # پوشه‌ای که فایل‌ها در آن قرار می‌گیرند
