name: Deploy to cPanel

on:
  push:
    branches:
      - master  # یا main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.1.0  # اطمینان از استفاده از آخرین نسخه
        with:
          server: ftp.avatarvps.com                 # دامنه یا IP سرور شما
          username: avatar@avatarvps.com            # نام کاربری FTP
          password: ${{ secrets.FTP_PASSWORD }}     # پسورد FTP از Secrets
          protocol: ftp                             # نوع پروتکل
          local-dir: ./                             # مسیر به دایرکتوری محلی
          server-dir: /public_html/javaher/         # پوشه‌ای که فایل‌ها در آن قرار می‌گیرند
          port: 21                                  # شماره پورت
